name: listroots
description: Mapping of root damage on cycle paths.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter_native_splash: ^2.2.16
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # user interface
  cupertino_icons: ^1.0.2
  map: ^1.3.4
  cached_network_image: ^3.2.2
  blobs: ^2.0.0

  # geo and sensors
  latlng: ^0.2.0
  maps_toolkit: ^2.0.1
  permission_handler: ^10.2.0
  sensors_plus: ^2.0.1

  # state management and routing
  go_router: ^5.1.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # persistence and database
  shared_preferences: ^2.0.15
  oauth2: ^2.0.1
  url_launcher: ^6.1.7
  uni_links: ^0.5.1
  path_provider: ^2.0.11
  geolocator: ^9.0.2
  supabase_flutter: ^1.2.2
  device_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_root.png"
  #image_path: "assets/icons/logo_green.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/road.png
    - assets/images/rootDmg.jpg
    - assets/icons/logo_green_rounded.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Medium.ttf
        - asset: fonts/IBMPlexSans-SemiBold.ttf
    - family: Swistblnk Monthoers
      fonts:
        - asset: fonts/Monthoers.ttf
