name: listroots
description: Mapping of root damage on cycle paths.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # user interface
  cupertino_icons: ^1.0.2
  map: ^1.3.4
  cached_network_image: ^3.2.2
  blobs: ^2.0.0

  # geo and sensors
  latlng: ^0.2.0
  maps_toolkit: ^2.0.1
  permission_handler: ^10.2.0
  sensors_plus: ^2.0.1

  # state management and routing
  go_router: ^5.1.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # persistence and database
  shared_preferences: ^2.0.15
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_root.png"
  #image_path: "assets/icons/logo_green.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/road.png
    - assets/images/rootDmg.jpg

  fonts:
    - family: IBM Plex Sans
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
        - asset: fonts/IBMPlexSans-Medium.ttf
        - asset: fonts/IBMPlexSans-SemiBold.ttf
    - family: Swistblnk Monthoers
      fonts:
        - asset: fonts/Monthoers.ttf
